server:
  port: 8081
  max-http-header-size: 102400
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 955099
    url: jdbc:mysql://127.0.0.1:3306/health_management?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
  mail:
    username: healthcare_group@yeah.net
    password: CRTXXAKKXSNGROZE
    host: smtp.yeah.net
    default-encoding: utf-8
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#        properties:
#          mail:
#            smtp:
#              ssl:
#                enable: true
  jackson:
    time-zone: GMT+8

### FreeMarker 配置
  freemarker:
    allow-request-override: false
  #Enable template caching.启用模板缓存。
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
   #设置面板后缀
    suffix: .ftl

# 设置单个文件最大内存
multipart:
  maxFileSize: 50Mb
# 设置所有文件最大内存
  maxRequestSize: 50Mb
# 自定义文件上传路径
web:
  upload-path: E:/javaProject/image/

